const categories = {
  Travel: [
    "Flights",
    "Trains",
    "Buses",
    "Cabs/Ride-Sharing",
    "Vehicle Rentals",
    "Fuel",
    "Taxis",
    "Visas",
    "Tour Packages",
    "Other",
  ],
  Food: [
    "Breakfast",
    "Lunch",
    "Dinner",
    "Snacks",
    "Desserts",
    "Beverages",
    "Takeout/Delivery",
    "Groceries",
    "Meal Prep Ingredients",
    "Dietary Supplements",
    "Meal Kits",
    "Other",
  ],
  Shopping: [
    "Clothes",
    "Electronics",
    "Home Goods",
    "Accessories",
    "Gifts",
    "Books",
    "Personal Care Products",
    "Groceries",
    "Online Shopping",
    "Sales/Discounts",
    "Other",
  ],
  Medical: [
    "Doctor's Visits",
    "Medications",
    "Health Check-ups",
    "Vaccinations",
    "Medical Equipment",
    "Lab Tests",
    "Emergency Services",
    "Counseling",
    "Physical Therapy",
    "Other",
  ],
  Housing: [
    "Rent/Mortgage",
    "Property Taxes",
    "Home Insurance",
    "Maintenance/Repairs",
    "Utilities",
    "Security Deposits",
    "Home Improvements",
    "Home Repairs",
    "Home Appliances",
    "Real Estate Agent Fees",
    "Other",
  ],
  PGs_Leasing: [
    "Rent",
    "Security Deposit",
    "Utilities",
    "Maintenance",
    "Furnishing",
    "Lease Agreement Fees",
    "PG Facility Fees",
    "Other",
  ],
  Bills: [
    "Electricity",
    "Water",
    "Gas",
    "Internet",
    "Phone Bill",
    "Cable/Satellite TV",
    "Trash Collection",
    "Subscription Services",
    "Property Taxes",
    "Internet Service Provider Fees",
    "Other",
  ],
  Study_Stationeries: [
    "Notebooks",
    "Pens/Pencils",
    "Textbooks",
    "Highlighters",
    "Binders",
    "Erasers",
    "Markers",
    "Calculator",
    "Other",
  ],
  Entertainment: [
    "Movies/TV Shows",
    "Concerts/Events",
    "Streaming Services",
    "Books",
    "Video Games",
    "Sports Events",
    "Museums/Exhibitions",
    "Other",
  ],
  Utilities: [
    "Electricity",
    "Water",
    "Gas",
    "Heating/Cooling",
    "Internet",
    "Trash Removal",
    "Sewer Charges",
    "Other",
  ],
  Transportation: [
    "Fuel",
    "Public Transit",
    "Car Maintenance",
    "Parking Fees",
    "Vehicle Insurance",
    "Tolls",
    "Other",
  ],
  Fitness: [
    "Gym Membership",
    "Fitness Classes",
    "Sports Equipment",
    "Personal Training",
    "Home Workout Equipment",
    "Yoga/Meditation Classes",
    "Athletic Wear",
    "Sports Club Memberships",
    "Fitness Equipment",
    "Other",
  ],
  Personal_Care: [
    "Haircuts/Styling",
    "Skincare Products",
    "Makeup",
    "Toiletries",
    "Nail Care",
    "Dental Care",
    "Grooming Supplies",
    "Hair Treatment Products",
    "Cosmetics",
    "Spa Treatments",
    "Other",
  ],
  Education: [
    "Tuition Fees",
    "Books and Supplies",
    "Online Courses",
    "Workshops/Seminars",
    "Certifications",
    "Study Materials",
    "Exam Fees",
    "Language Learning",
    "Test Preparation",
    "Other",
  ],
  Subscriptions: [
    "Streaming Services",
    "Magazines/Journals",
    "Software",
    "News Services",
    "Membership Clubs",
    "Apps/Online Tools",
    "Other",
  ],
  Gifts: [
    "Birthday Gifts",
    "Holiday Gifts",
    "Anniversary Gifts",
    "Thank You Gifts",
    "Special Occasion Gifts",
    "Personalized Gifts",
    "Gift Cards",
    "Other",
  ],
  Childcare: [
    "Daycare/Preschool",
    "Babysitting",
    "Children's Activities/Classes",
    "School Supplies",
    "Clothing",
    "Health Care",
    "Toys/Games",
    "Other",
  ],
  Insurance: [
    "Health Insurance",
    "Life Insurance",
    "Auto Insurance",
    "Home Insurance",
    "Travel Insurance",
    "Property Insurance",
    "Business Insurance",
    "Dental Insurance",
    "Disability Insurance",
    "Other",
  ],
  Home_Improvement: [
    "Renovations",
    "Painting",
    "Furniture",
    "Landscaping",
    "DIY Projects",
    "Appliances",
    "Decorating",
    "Roofing",
    "Plumbing",
    "Electrical Repairs",
    "Other",
  ],
  Hobbies: [
    "Craft Supplies",
    "Musical Instruments",
    "Art Supplies",
    "Gardening",
    "Photography",
    "Collectibles",
    "Sports Equipment",
    "Other",
  ],
  Pets: [
    "Food",
    "Veterinary Care",
    "Grooming",
    "Toys",
    "Training",
    "Pet Insurance",
    "Boarding/Daycare",
    "Other",
  ],
};

export default categories;
