// src/incomeSources.js
const incomeSources = {
  Businessmen: [
    "Business Income",
    "Freelance/Consulting",
    "Investments",
    "Rental Income",
    "Royalties",
    "Interest Income",
    "Dividends",
    "Gifts/Cards",
    "Capital Gains",
    "Intellectual Property Licensing",
    "Partnership/Shareholder Income",
  ],
  Housewife: [
    "Household Allowance",
    "Freelance/Part-time Work",
    "Small Business Income",
    "Gifts/Inheritance",
    "Investment Income",
    "Rental Income",
    "Child Support",
    "Side Business",
    "Home-based Business Income",
    "Freelance Writing/Blogging",
  ],
  Employee: [
    "Salary/Wages",
    "Bonuses/Commissions",
    "Freelance/Side Jobs",
    "Investments",
    "Side Business",
    "Pension Contributions",
    "Rental Income",
    "Tax Refunds",
    "Gifts/Cards",
    "Stock Options/Equity Compensation",
    "Health Reimbursements/Benefits",
    "Year-end Performance Bonuses",
  ],
  Student: [
    "Scholarships/Grants",
    "Part-time Job",
    "Freelance Work",
    "Allowance from Parents",
    "Project Stipends",
    "Small Business Income",
    "Gifts/Cards",
    "Internship Stipends",
    "Student Loans (for educational purposes)",
    "Tutoring/Coaching Income",
  ],
  Retired: [
    "Pension/Retirement Income",
    "Social Security/Benefits",
    "Rental Income",
    "Side Business",
    "Investment Returns",
    "Dividends",
    "Interest Income",
    "Gifts/Cards",
    "Annuities",
    "Social Security Payouts",
    "Reverse Mortgage Payments",
    "Retirement Savings Withdrawals",
  ],
  "Door-to-Door Seller": [
    "Daily Sales Income",
    "Freelance Work",
    "Small Business Income",
    "Investment Income",
    "Gifts/Cards",
    "Seasonal Product Sales",
    "Direct Selling Income",
    "Mobile Retail Sales",
    "Crafts and Handmade Goods Sales",
  ],
  Worker: [
    "Daily Wages",
    "Overtime Pay",
    "Side Business",
    "Freelance Work",
    "Temporary/Contract Jobs",
    "Bonuses/Commissions",
    "Gifts/Cards",
    "Hourly Wages",
    "Shift Allowances",
    "Union Benefits",
    "Performance Bonuses",
    "Holiday/Seasonal Work Income",
  ],
};

export default incomeSources;
